### ISSUE TITLE
Fail to compile F90 files.

### ISSUE THREAD

**Issue by drschrank** [jvencels/EOF-Library#2]
I don't seem to be able to compile Elmer2OpenFOAM.F90 or OpenFOAM2Elmer.F90. In both cases, I get an error that "elmer_comm_world" has no implicit type. I'm not sure what the symbol is suppose to be pointing to.

Elmer is installed in my home directory rather than /usr/local/, but I do have the installation directory in my PATH. I'm using Elmer version 8.1.

**Comment by jvencels** [comment]
Try downloading/cloning and compiling Elmer's development version from https://github.com/ElmerCSC/elmerfem

Also, current version of EOF-Library seems to work with OpenFOAM 5.0 compiled from source.
