### ISSUE TITLE
Unable to Run Simulation

### ISSUE THREAD

**Issue by JabirSS** [jvencels/EOF-Library#4]
Dear @jvencels ,

Thank you for creating EOF library! I was excited when I found out it existed as it perfectly suite my needs.
I am trying to simulate a simple problem using EOF library: basically the oscillation of a droplet of an electrically conducting fluid due to surface tension in the presence of a constant magnetic field, however after trying for a couple of days, the simulation keeps crashing right after the time loop is started with the following error:
`ERROR:: OpenFOAM2ElmerSolver: Elmer #1 has 5775 elements, OpenFOAM found 0`
and I am not sure why. 

[EOF_dropletInB.zip](https://github.com/jvencels/EOF-Library/files/3011914/EOF_dropletInB.zip)

I attached the problem files here and would greatly appreciate it if you could check it out and help me figure out what's wrong.

Best regards,
Jabir

**Comment by jvencels** [comment]
Hi,

*1)***Body 4
   Target Bodies(1) = 5
   Name = "FluidDomain"
   Equation = 1
   Material = 4
End

*2) *$ FluidDomain = 11

Shouldn't fluid domain be #11?

Juris

**Comment by JabirSS** [comment]
Yes! Now after changing other target bodies numbers as well it's working fine, thank you.
Since I am dealing with a static magnetic field in my case, how do you suggest that I change the settings of Elmer sif file? Since I don't think I need the Magnetodynamics2DHarmonic solver...

**Comment by jvencels** [comment]
Refer to Elmer Models Manual:
http://www.nic.funet.fi/index/elmer/doc/ElmerModelsManual.pdf 
<http://www.nic.funet.fi/index/elmer/doc/ElmerModelsManual.pdf>

I am providing support and can help with your problem, but that requires 
either collaboration or financing.

Juris

**Comment by JabirSS** [comment]
Of course your EOF papers will be cited in addition to your help and support being acknowledged properly in future papers. To give you a little background, I am trying to use the EOF library for validation and comparison with a particle based free surface MHD solver. 

If you are willing to help, then right now I have simplified the problem further by just having the elmer mesh and openfoam mesh to be the same and only set the magnetic field flux density at the boundaries. I tried to use the WhitneyAVSolver to set these values but I can't see the effect in the solution at all. 
[EOF_dropletInB.zip](https://github.com/jvencels/EOF-Library/files/3017282/EOF_dropletInB.zip)

Also, could you please direct me to where I can find the Hartmann flow example EOF files? That would be very helpful.

Thank you,

Jabir

**Comment by jvencels** [comment]
In science it is mandatory to refer the used work, this does not count 
as a collaboration or giving any favor.

Currently, EOF-Library development is solely my initiative, there is no 
public funding involved. In order to keep things moving, I have to 
prioritize time and effort. I do not know what kind of help I could 
expect from you.

Contact me if you have any proposal, my email vencels@eof-library.com

Juris
